server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
jwt:
  secret: ${KEYSECRET_SECURITY}
  expiration: ${EXPIRE_DAYS_SECURITY}

user-microservice:
  url: ${URL_USER_MICROSERVICE}

messenger-microservice:
  url: ${URL_MESSENGER_MICROSERVICE}
